### ISSUE TITLE
Paddle.authenticate() throwing "no match" errors

### ISSUE THREAD

**Issue by srevenant** [minijackson/paddle#10]
We are getting errors about patterns not matching and our GenServer then dies.  Would it be a good idea to include a fourth default case:

   _ -> {?}

At this location:
    https://github.com/minijackson/paddle/blob/master/lib/paddle.ex#L179

**Comment by minijackson** [comment]
Yep, you're right. It also made me realize that I didn't put the typespec for the authenticate operation, thanks !

**Comment by minijackson** [comment]
For future reference, can you give me the type of error that you got ?

**Comment by srevenant** [comment]
I did still have the stack around:

 ** (exit) exited in: GenServer.call(Paddle, {:authenticate, 'cn=zz,dc=com', 'pwd'}, 5000)
 ** (EXIT) an exception was raised:
 ** (CaseClauseError) no case clause matching: {:error, {:gen_tcp_error, :closed}}
    (paddle) lib/paddle.ex:179: Paddle.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

**Comment by minijackson** [comment]
Thanks !
