### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by srevenant** [minijackson/paddle#12]
phoenix_1   | 22:34:50.538  level=error GenServer Paddle terminating
phoenix_1   | ** (CaseClauseError) no case clause matching: :other
phoenix_1   |     (paddle) lib/paddle.ex:612: Paddle.clean_eldap_search_results/1
phoenix_1   |     (paddle) lib/paddle.ex:206: Paddle.handle_call/3
phoenix_1   |     (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
phoenix_1   |     (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
phoenix_1   |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

I don't know if it is in your plans, but have you considered setting up a supervisor process so when it does die like this, we can recover?

Thanks,

**Comment by minijackson** [comment]
I was planning to add a supervisor when I would work on multiple connections (#4), but you're absolutely right, it's kind of really important, sorry about that

**Comment by srevenant** [comment]
it is becoming a non-starter for us.  It seems to die quite frequently and for no reason, so most of the time we try to use the service it is dead.
