### ISSUE TITLE
Paddle enlève la possibilité de passer une liste d'hôtes à eldap.

### ISSUE THREAD

**Issue by tchoutri** [minijackson/paddle#14]
La signature de `eldap:open` est `open([Host], [Option]) -> {ok, Handle} | {error, Reason}`, et pourtant dans la configuration de Paddle, il ne semble être prévu qu'un seul hôte soit supporté, ainsi que dans [paddle.ex](https://github.com/minijackson/paddle/blob/master/lib/paddle.ex#L135) où l'hôte (unique, donc) est mis dans une liste.
C'est relativement dommage si on a une réplique du LDAP et que le primaire tombe.

(PS: j'espère que tu t'amuses au Canada :heart:)

**Comment by minijackson** [comment]
Et voilà ! Je n'ai pas vérifié le comportement pour l'instant, mais lorsque le LDAP primaire tombe, ça devrait restart Paddle (à la prochaine requête ?) et il devrait se reconnecter et choisir le suivant (regarde l'option timeout)

(PS: Shhh 😛)
