### ISSUE TITLE
Ajouter un flag inet6

### ISSUE THREAD

**Issue by tchoutri** [minijackson/paddle#15]
Yo, y'a une option pour avoir l'IPv6 dans `eldap` un peu planquée dans les notes de version.
Apparemment ça fonctionne avec `:eldap.open(['cimmeria.rezel.enst.fr'], [tcpopts: [:inet6], port: 389])`, du coup si y'a moyen d'avoir un booléen `v6?`, ça serait chouette :)

**Comment by minijackson** [comment]
Hmm, je me demande si ça serait pas plus malin à ce moment là de carrément rajouter une options `:tcpopts`. Mais c'est vrai que comme l'IPv5 peut être une option courante, la mettre de manière plus accessible serait intéressant.

**Comment by tchoutri** [comment]
ouip' la majorité des options *tcp* sont inutiles. Après, y'a aussi les options *ssl* qui sont intéressantes. Par exemple, upgrader la connexion en `STARTTLS`, ou bien #9 :)

**Comment by minijackson** [comment]
Et voilà ! (désolé du retard, j'ai mes finaux en ce moment)
