### ISSUE TITLE
Application exits when LDAP is not reachable

### ISSUE THREAD

**Issue by shamanime** [minijackson/paddle#20]
Hello!

Here's my scenario:

I have built an umbrella project with 2 applications: LdapInterface, which does some LDAP user management, and a Slack bot which passes user commands to the other app.

Sometimes our LDAP will be unavailable due to external factors, say, VPN hiccups, and connecting to LDAP would fail preventing the app from starting. When this happens, my Slack bot doesn't connect as well.

Instead, I wanted to give feedback on Slack when the LDAP connection is not available.

This may not be the best approach and I may be missing something, but here's what I did:
Forked the repo and let the app start without holding a connection to LDAP, and when a message arrives it returns {:error, :not_connected} so I can gracefully handle it, send a message on Slack and try a reconnection.

Those are the changes: https://github.com/shamanime/paddle/commit/7efb4a0f8d3a87b27ac12da9035436bcb1de22fc

This solves my issue. Is there a better approach to achieve this result? Do you think this would be valuable for anyone else? Would you be interested in a PR?

Thank you for your work on this project!

**Comment by minijackson** [comment]
Hello to you!

This looks good, I'd love you to make a PR for that!

I also would like some tests but not sure how to proceed about that since the configuration is central to the whole test base. Do you have any ideas?

Thank you!

**Comment by shamanime** [comment]
Wow I was so blind trying to come up with something quickly that I forgot about the tests. I’m sorry. 

Yeah. This seems tricky. 
What if we change start_link to also accept connection params and introduce a reconnect/1 method? This method would close the current connection and open a new one. 

I’ll do some experiments and give feedback.

**Comment by viniciussbs** [comment]
Hi! Are you planning a new release since #21 is merged? I also need this solution. I'm currently point to `master`.

**Comment by minijackson** [comment]
Sure! This should be all done, thank you for reminding me, and sorry about that.

Closing since it's fixed :wink:
