### ISSUE TITLE
No success in class generation

### ISSUE THREAD

**Issue by dvbmgr** [minijackson/paddle#45]
Dear all,

First of, thanks for the amazing work with this library.

I am currently trying to generate a class for `inetorgperson.schema`, but with no success so far, and I would be really grateful if you could provide some hints on how to solve my issue. Please have my apologies, as I am still pretty new to Elixir (and LDAP, actually).

I have my schema installed in `/etc/openldap/schema/*.schema`, and thus have configured 

```elixir
config :paddle, Paddle,
  host: "myserver.com"
  base: "dc=myserver,dc=com",
  ssl: false,
  account_subdn: "ou=users",
  port: 389,
  schema_files: Path.wildcard("/etc/openldap/schema/*.schema")
```

as suggested by the [documentation](https://hexdocs.pm/paddle/Paddle.html#module-configuration).

I then have created, in a file `api/ldap.ex`, my helper module to authenticate my users, etc., and, after the module

```elixir
defmodule Api.Ldap do
    ....
end

require Paddle.Class.Helper
Paddle.Class.Helper.gen_class_from_schema(Api.Ldap.InetOrgPerson, ["inetOrgPerson"], "ou=users")
```

If I get this right, the first parameter tells the macro to generate a module named `Api.Ldap.InetOrgPerson`, based on the LDAP schema `inetOrgPerson`, and that such entries should be stored under, in my case, `ou=users,dc=myserver,dc=com`. If I am not mistaken, Paddle is able to guess  in which `.schema` file `inetOrgPerson` is defined, but this might really be where I get this wrong. However, I don't understand how it should then be specified which `.schema` defines `inetOrgPerson`.

Indeed, I get the following error from `mix`:

```
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Compiling 20 files (.ex)

== Compilation error in file lib/ldap.ex ==
** (RuntimeError) Missing object classe(s) definition(s): inetOrgPerson
    lib/paddle/schema_parser.ex:114: Paddle.SchemaParser.filter_definitions/3
    lib/paddle/schema_parser.ex:48: Paddle.SchemaParser.attributes/1
    lib/paddle/class.ex:186: Paddle.Class.Helper."MACRO-gen_class_from_schema"/6
    expanding macro: Paddle.Class.Helper.gen_class_from_schema/3
    lib/ldap.ex:38: (file)
```

Which would mean, I think, that Paddle is not able to guess where to find the `inetOrgPerson` definition.

Could you indicate me
- if this is really the issue?
- how to inform Paddle which file it should be reading the class from?
- what is your process for debugging those kind of mistakes ?

Best regards

**Comment by minijackson** [comment]
Hello, and thank you for the kind words!

The error `Missing object classe(s) definition(s): inetOrgPerson` does indeed indicate that Paddle cannot find the `inetOrgPerson` object class form your schemas.

If on my computer I have this:

```
% iex -S mix
iex(1)> require Paddle.Class.Helper
Paddle.Class.Helper
iex(2)> Paddle.Class.Helper.gen_class_from_schema(Thing.InetOrgPerson, "inetOrgPerson", "ou=users", :uid)
warning: the Paddle.Class protocol has already been consolidated, an implementation for Thing.InetOrgPerson has no effect. If you want to implement protocols after compilation or during tests, check the "Consolidation" section in the Protocol module documentation
  iex:2: (file)

{:module, Paddle.Class.Thing.InetOrgPerson,
 <<70, 79, 82, 49, 0, 0, 9, 200, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 1, 43,
   0, 0, 0, 24, 39, 69, 108, 105, 120, 105, 114, 46, 80, 97, 100, 100, 108, 101,
   46, 67, 108, 97, 115, 115, 46, 84, 104, ...>>, {:__impl__, 1}}
```

Which tells me that it does find the `inetOrgPerson` object class on my end.

(Note that I specified `:uid` as unique identifier, because `inetOrgPerson` does not have any `MUST` attributes, so Paddle can't figure out a default one. If you do not specify one, you'd get an incomprehensible error which I definitely should fix)

For me, I have `inetOrgPerson` in the `inetorgperson.schema` right at the end:

```bash
# inetOrgPerson
# The inetOrgPerson represents people who are associated with an
# organization in some way.  It is a structural class and is derived
# from the organizationalPerson which is defined in X.521 [X521].
objectclass	( 2.16.840.1.113730.3.2.2
    NAME 'inetOrgPerson'
	DESC 'RFC2798: Internet Organizational Person'
    SUP organizationalPerson
    STRUCTURAL
	MAY (
		audio $ businessCategory $ carLicense $ departmentNumber $
		displayName $ employeeNumber $ employeeType $ givenName $
		homePhone $ homePostalAddress $ initials $ jpegPhoto $
		labeledURI $ mail $ manager $ mobile $ o $ pager $
		photo $ roomNumber $ secretary $ uid $ userCertificate $
		x500uniqueIdentifier $ preferredLanguage $
		userSMIMECertificate $ userPKCS12 )
	)
```

> how to inform Paddle which file it should be reading the class from?

You normally don't need to specify from which file Paddle needs to get the class, if you've specified all the schema files in the `:schema_files` configuration, all the class parsed from these files should be available.

For how to debug the process: if you have the Logger level set to info, and you clean and recompile Paddle, you shoud be able to see the files that it parses:

```
23:18:47.173 [info]  Loading /etc/openldap/schema/collective.schema
23:18:47.174 [info]  Loading /etc/openldap/schema/corba.schema
23:18:47.174 [info]  Loading /etc/openldap/schema/core.schema
23:18:47.175 [info]  Loading /etc/openldap/schema/cosine.schema
23:18:47.178 [info]  Loading /etc/openldap/schema/duaconf.schema
23:18:47.179 [info]  Loading /etc/openldap/schema/dyngroup.schema
23:18:47.179 [info]  Loading /etc/openldap/schema/inetorgperson.schema     <-- Hello :)
23:18:47.179 [info]  Loading /etc/openldap/schema/java.schema
23:18:47.180 [info]  Loading /etc/openldap/schema/misc.schema
23:18:47.180 [info]  Loading /etc/openldap/schema/nis.schema
23:18:47.180 [info]  Loading /etc/openldap/schema/openldap.schema
23:18:47.180 [info]  Loading /etc/openldap/schema/pmi.schema
23:18:47.181 [info]  Loading /etc/openldap/schema/ppolicy.schema
```

Another thing to note is that the schema files are parsed at compile time, so if you change the `:schema_files` configuration, you will probably want to clean and recompile paddle.

Is there something different on your end?

Cheers

**Comment by dvbmgr** [comment]
Hi,

Thank you so much for your answer!

I think I understood what didn't go well: I didn't rebuild Paddle after changing the `:schema_files` config, and it seems that it's needed in order to make this work.

If this is indeed the case, would it be possible to mention it in the docs ?

Best regards

**Comment by minijackson** [comment]
It is definitely a pitfall that wants to be documented!

I'll push a commit soon, but it feels awkward to do a release just for that, and since there's not much happening, I don't know when the change in doc will be visible on https://hexdocs.pm

**Comment by dvbmgr** [comment]
Thank you very much! yes, it doesn't make sense to publish a version just for that! (;

Best regards!
