### ISSUE TITLE
authenticate assumes all users in one ou, always uses uid attribute

### ISSUE THREAD

**Issue by andymc** [minijackson/paddle#7]
In our ldap, we have a whole tree of different organizations - for example, my dn looks something like this: 
cn=andymc,ou=myOrg,ou=New York,ou=US,o=myCo 

and other users might be in other countries or states, etc... 
It would be great if authenticate could accept a form of username that was just the whole DN, and didn't mess with it at all. If I have time I'll implement it, but not sure how you'd like it done.

**Comment by minijackson** [comment]
There's a way to specify the DN (without the base) in the authenticate function, you can do it like this:

```elixir
Paddle.authenticate([cn: "andymc", out: "myOrg", ou: "New York", ou: "US", o: "myCo"], "mypasswd")
```

But you're right, forcing the user to use uid as an identifier isn't standard, that should be configurable, I'll fix it in a moment.

Please contribute to this project if you want to, I'll be happy to explain how this lib works and merge PRs ;-)
