### ISSUE TITLE
Ability to configure SSL certificates for LDAPS

### ISSUE THREAD

**Issue by srevenant** [minijackson/paddle#9]
In testing this my connection is failing, but I can connect with ldapsearch to my ldapserver.  However, ldapsearch does report that it doesn't like the certificate because the root CA is untrusted.  My speculation is that this might be happening under the hood, and it is just bubbling up to the top as a connection failure?

**Comment by srevenant** [comment]
On further guess/investigation, it appears that the underlying erlang ldap library simply uses openldap, and `/etc/openldap/ldap.conf` is supported.  I'll configure things from there, but it might be good to note this somewhere in the docs.

**Comment by minijackson** [comment]
Are you sure ? By reading the eldap source code, it seems to me that it is a full implementation of the LDAP protocol (and uses erlang's [ssl](http://erlang.org/doc/man/ssl.html) module for connection and certificate validation)

Have you managed to fix your issue by modifying the `ldap.conf` file ?

**Comment by srevenant** [comment]
Yes, I can verify the problem is resolved by hardwiring the certificate in `ldap.conf` and/or for debugging also just disabling certificate verification (TLS_REQCERT ALLOW).

**Comment by minijackson** [comment]
I'm still a bit confused about the `ldap.conf` fix, but I still added the `:sslopts` from which you can specify a certificate to pass to Erlang's [`:ssl` module](http://erlang.org/doc/man/ssl.html)
